/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Clases.GraficadorClasico;
import Clases.Integral2;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.PI;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.edisoncor.gui.panel.PanelImage;

/**
 *
 * @author Reymundo Tenorio
 */
public class IntegralVentana extends javax.swing.JFrame {

    /**
     * Creates new form Integral
     */
    public IntegralVentana() {
        initComponents();
        this.setResizable(false);
        txtFuncion.requestFocus();
        
        txtLimitA.setTransferHandler(null);
        txtLimitB.setTransferHandler(null);
       
        stopper = new Timer(2500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Procesando.dispose();
            }
        });
        
    }
    
    
    ProcesandoInfo Procesando = new ProcesandoInfo(this, true);
    static Timer stopper ;
    
     public  void setProcess() {
        setWaitProcess();
    }
    
    public void setWaitProcess() {
         if (!stopper.isRunning()) {
            stopper.start();
        }
        Procesando.setVisible(true);
        Procesando.toFront();
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCancelar1 = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        txtLimitB = new javax.swing.JTextField();
        txtLimitA = new javax.swing.JTextField();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        rdRadianes = new javax.swing.JRadioButton();
        rdGrados = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnCancelar1.setText("Nuevo");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar1);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcular);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Como Usar La Aplicación:\n\nPara Potencias:\n\t(Expresión)^(Potencia):   (3)^(X)+32+(4)^(2+X)\n\nPara Raices:\n\t(Radicando)^(1/Índice Raíz):   (X)^(1/2) <Raíz Cuandrada>\n\nPara Funciones Trigonometricas (Seno, Coseno, Tangente):\n\t(Cos,Tan,Sen): \tSen(34*X)+Tan(1)+32+(X)^(2+4-Cos(3))");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evaluar Integral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        txtFuncion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 322;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(81, 6, 0, 0);
        jPanel1.add(txtFuncion, gridBagConstraints);

        txtLimitB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLimitBKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 33, 0, 0);
        jPanel1.add(txtLimitB, gridBagConstraints);

        txtLimitA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLimitAKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 116, 68, 0);
        jPanel1.add(txtLimitA, gridBagConstraints);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Integral.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 154;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 130, 0, 0);
        jPanel1.add(panelImage1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("dX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(81, 10, 0, 91);
        jPanel1.add(jLabel2, gridBagConstraints);

        buttonGroup1.add(rdRadianes);
        rdRadianes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdRadianes.setSelected(true);
        rdRadianes.setText("Radianes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 0, 0, 0);
        jPanel1.add(rdRadianes, gridBagConstraints);

        buttonGroup1.add(rdGrados);
        rdGrados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdGrados.setText("Grados");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 0, 0, 0);
        jPanel1.add(rdGrados, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Resultado en: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 6, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setPreferredSize(new java.awt.Dimension(285, 50));

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 102, 153));
        lblResultado.setText("El Resultado de la Integral Es: ");
        jPanel5.add(lblResultado);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(708, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLimitBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLimitBKeyTyped
char a = evt.getKeyChar();



if(!Character.isDigit(a)&&!Character.isISOControl(a)&&a!='.'&&a!='-'){
    
    Toolkit.getDefaultToolkit().beep();
    evt.consume();
    
}

if(a=='.'&&txtLimitB.getText().trim().contains(".")){
        Toolkit.getDefaultToolkit().beep();
    evt.consume();
}

if(a=='-'&&txtLimitB.getCaretPosition()!=0){
       Toolkit.getDefaultToolkit().beep();
    evt.consume();

}


if(a=='-'&&txtLimitB.getText().trim().contains("-")&&txtLimitB.getCaretPosition()!=0){
        Toolkit.getDefaultToolkit().beep();
    evt.consume();
}
// TODO add your handling code here:
    }//GEN-LAST:event_txtLimitBKeyTyped

    private void txtLimitAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLimitAKeyTyped
char a = evt.getKeyChar();



if(!Character.isDigit(a)&&!Character.isISOControl(a)&&a!='.'&&a!='-'){
    
    Toolkit.getDefaultToolkit().beep();
    evt.consume();
    
}

if(a=='.'&&txtLimitA.getText().trim().contains(".")){
        Toolkit.getDefaultToolkit().beep();
    evt.consume();
} 

if(a=='-'&&txtLimitA.getCaretPosition()!=0){
       Toolkit.getDefaultToolkit().beep();
    evt.consume();

}

if(a=='-'&&txtLimitA.getText().trim().contains("-")){
        Toolkit.getDefaultToolkit().beep();
    evt.consume();
}


// TODO add your handling code here:
    }//GEN-LAST:event_txtLimitAKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

       setProcess();

        try{
        Calcular();
        }catch(Exception Ex){
            JOptionPane.showMessageDialog(this, "Error al Evaluar La Integral,"
                    + " Verifique Si La Funcion Es Valida y Existe, y Si Sus Limites"
                    + " Son Validos y Existen. Recuerde Verificar y Escribir de Manera"
                    + " Adecuada Su Funcion", "Verificar", JOptionPane.ERROR_MESSAGE);
          
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
Limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    
    public void Calcular(){
        
String Funcion=txtFuncion.getText().toLowerCase().trim();
String BaseB = txtLimitB.getText().toLowerCase().trim();
String BaseA = txtLimitA.getText().toLowerCase().trim();



lblResultado.setText("El Resultado de la Integral Es: ");

if("".equals(Funcion)){
    JOptionPane.showMessageDialog(this, "Ingrese La Función a Evaluar de la Integral"
       , "Ingrese Función", JOptionPane.ERROR_MESSAGE);
    return;
}

if("".equals(BaseA)){
    JOptionPane.showMessageDialog(this, "Ingrese El Límite Inferior de La Integral"
       , "Ingrese Límite Inferior", JOptionPane.ERROR_MESSAGE);
    return;
}

if("".equals(BaseB)){
    JOptionPane.showMessageDialog(this, "Ingrese El Límite Superior de La Integral"
       , "Ingrese Límite Superior", JOptionPane.ERROR_MESSAGE);
    return;
}

Integral2 Integral = new Integral2();

Integral.CalcularIntegral(Funcion, BaseA, BaseB);

if(rdGrados.isSelected()){
  
    double Resultado = 0;
    Resultado = Double.parseDouble(Integral.getArea());
    Resultado = Resultado*180;
    Resultado = Resultado / PI;
    
    
    JOptionPane.showMessageDialog(this, "El Resultado de la Integral Es: "
        +(Resultado)+" º", "Resultado", JOptionPane.INFORMATION_MESSAGE);

      lblResultado.setText("El Resultado de la Integral Es: "
        +(Resultado)+" º");
    
}
else{
JOptionPane.showMessageDialog(this, "El Resultado de la Integral Es: "
        +Integral.getArea()+" rad", "Resultado", JOptionPane.INFORMATION_MESSAGE);

      lblResultado.setText("El Resultado de la Integral Es: "
        +Integral.getArea()+" rad");
}


new GraficadorClasico(Funcion).setVisible(true);

    }

    public IntegralVentana(JButton btnCalcular, JButton btnCancelar, JButton btnCancelar1, JLabel jLabel1, JLabel jLabel2, JPanel jPanel1, JPanel jPanel2, JPanel jPanel3, JPanel jPanel4, JScrollPane jScrollPane1, JTextArea jTextArea1, JLabel lblResultado, PanelImage panelImage1, JTextField txtFuncion, JTextField txtLimitA, JTextField txtLimitB) throws HeadlessException {
        this.btnCalcular = btnCalcular;
        this.btnCancelar = btnCancelar;
        this.btnCancelar1 = btnCancelar1;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jPanel3 = jPanel3;
        this.jPanel4 = jPanel4;
        this.jScrollPane1 = jScrollPane1;
        this.jTextArea1 = jTextArea1;
        this.lblResultado = lblResultado;
        this.panelImage1 = panelImage1;
        this.txtFuncion = txtFuncion;
        this.txtLimitA = txtLimitA;
        this.txtLimitB = txtLimitB;
    }
    
   public static IntegralVentana Ventana;
    
    public void Limpiar(){
        
        txtFuncion.setText("");
        txtLimitA.setText("");
        txtLimitB.setText("");
        lblResultado.setText("El Resultado de la Integral Es: ");
        rdRadianes.setSelected(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IntegralVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        
         try 
    {
     
UIManager.setLookAndFeel( new com.nilo.plaf.nimrod.NimRODLookAndFeel());
        

	      
    } catch (UnsupportedLookAndFeelException e) 
    {
            JOptionPane.showMessageDialog(null, "Error Al Iniciar Look and Feel","Error",JOptionPane.ERROR_MESSAGE);
    }
                 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IntegralVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblResultado;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private javax.swing.JRadioButton rdGrados;
    private javax.swing.JRadioButton rdRadianes;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtLimitA;
    private javax.swing.JTextField txtLimitB;
    // End of variables declaration//GEN-END:variables
}
